#!/usr/bin/env node

/**
 * Module dependencies.
 */

var PORT = process.env.PORT || 3000;
var serve = require('koa-static');
var route = require('koa-route');
var koa = require('koa');

/**
 * Expose `app`.
 */

exports = app = koa();

/**
 * Setup static directory.
 */

app.use(serve('client'));

/**
 * Configure routes.
 */

var routes = require('./lib/routes.js');
app.use(route.get('/', routes.index));
app.use(route.post('/api/create', routes.create));
app.use(route.post('/api/remove', routes.remove));
app.use(route.post('/api/results', routes.results));

/**
 * Listen on PORT.
 */

app.listen(PORT);
console.log('listening on port ' + PORT);
