#!/usr/bin/env node

/**
 * Module dependencies.
 */

var parser = require('koa-bodyparser');
var PORT = process.env.PORT || 3000;
var serve = require('koa-static');
var route = require('koa-route');
var koa = require('koa');

/**
 * Expose `app`.
 */

exports = app = koa();

/**
 * Setup static directory.
 */
app.use(serve('client-react/static'));

/**
 * Use body parser.
 */

app.use(parser());

/**
 * Configure routes.
 */

var routes = require('./lib/routes.js');
app.use(route.get('/', routes.index));
app.use(route.get('/game', routes.index));
app.use(route.post('/connect', routes.connect, null));
app.use(route.get('/api/user', routes.user.list));
app.use(route.post('/api/user', routes.user.create, null));
app.use(route.get('/api/game', routes.game.list));
app.use(route.get('/api/game/:id', routes.game.fetch));
app.use(route.post('/api/game', routes.game.create, null));
app.use(route.delete('/api/game/:id', routes.game.delete));
app.use(route.delete('/api/user/:name', routes.user.remove));

/**
 * Listen on PORT.
 */

app.listen(PORT);
console.log('listening on port ' + PORT);
