#!/usr/bin/env node

/**
 * Module dependencies.
 */

var request = require('superagent');
var User = require('./lib/user');
var fmt = require('./lib/fmt');
var co = require('co');

/**
 * Run the program.
 */

co(main());

/**
 * define Main function.
 */

function *main() {
  var ladder = yield User.find({});
  ladder = ladder.sort(sortByRating).slice(0, 5);
  post(ladder);
}

/**
 * Send post.
 */

function post(ladder) {
  var uri = 'https://hooks.slack.com/services/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';
  request
    .post(uri)
    .send(slack(ladder))
    .end(function(err, res) {
      process.exit(code=0);
    });
}

/**
 * Format body request to how slack wants it.
 */

function slack(ladder) {
  var text = '';
  for (var i = 0; i < ladder.length; i++) {
    var p = ladder[i];
    text += fmt('%d. %s, %s, %s games\n', i, p.name, p.rating, p.games);
  }
  return JSON.stringify({ text: text });
}

/**
 * Sort by rating.
 */

function sortByRating(a, b) {
  return a.rating > b.rating ? -1 : 1;
}
