/**
 * Created by karl on 05/02/2017.
 */
'use strict';

export const FETCH_USERS_REQUEST = 'FETCH_USERS_REQUEST';
export const FETCH_USERS_SUCCESS = 'FETCH_USERS_SUCCESS';
export const FETCH_USERS_ERROR = 'FETCH_USERS_ERROR';
export const NEW_USER_REQUEST = 'NEW_USER_REQUEST';
export const NEW_USER_SUCCESS = 'NEW_USER_SUCCESS';
export const NEW_USER_ERROR = 'NEW_USER_ERROR';

export const FETCH_GAMES_REQUEST = 'FETCH_GAMES_REQUEST';
export const FETCH_GAMES_SUCCESS = 'FETCH_GAMES_SUCCESS';
export const FETCH_GAMES_ERROR = 'FETCH_GAMES_ERROR';
export const NEW_GAME_REQUEST = 'NEW_GAME_REQUEST';
export const NEW_GAME_SUCCESS = 'NEW_GAME_SUCCESS';
export const NEW_GAME_ERROR = 'NEW_GAME_ERROR';

export const UI_DRAWER_TOGGLE = 'UI_DRAWER_TOGGLE';

export const PROFILE_CONNECT_REQUEST = 'PROFILE_CONNECT_REQUEST';
export const PROFILE_CONNECT_SUCCESS = 'PROFILE_CONNECT_SUCCESS';
export const PROFILE_CONNECT_ERROR = 'PROFILE_CONNECT_ERROR';
export const PROFILE_LOGOUT_REQUEST = 'PROFILE_LOGOUT_REQUEST';
export const PROFILE_LOGOUT_SUCCESS = 'PROFILE_LOGOUT_SUCESS';

export const UI_MODAL_NEW_GAME_TOGGLE = 'UI_MODAL_NEW_GAME_TOGGLE';
export const UI_MODAL_NEW_USER_TOGGLE = 'UI_MODAL_NEW_USER_TOGGLE';
export const UI_MODAL_LOGIN_TOGGLE = 'UI_MODAL_LOGIN_TOGGLE';
export const UI_ADMIN_ACTION_TOGGLE = 'UI_ADMIN_ACTION_TOGGLE';